server:
  port: 81
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 39.99.162.169:8849 # 修改本机的host文件
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现
          lower-case-service-id: true # admin-service -> ADMIN-SERVICE 小驼峰路由规则
      routes:
        - id: admin-service_router
          uri: lb://admin-service # 转发到的目的地
          predicates:
            - Path=/admin/**
        - id: test_router
          uri: http://www.baidu.com/
          predicates:
            - Path=/test